version: '2'
services:
  minio:
    image: quay.io/minio/minio
    networks:
      - airflow
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    extra_hosts:
      - "host.docker.internal:host-gateway"  
    restart: always
  local_db:
    image: postgres
    networks:
      - airflow    
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGPORT: 5433
    ports:
      - 5433:5433
    extra_hosts:
      - "host.docker.internal:host-gateway"      
  pgadmin:
    image: dpage/pgadmin4
    networks:
      - airflow
    ports:
      - 5050:8910
    environment:
    - PGADMIN_DEFAULT_EMAIL=name@example.com
    - PGADMIN_DEFAULT_PASSWORD=admin
    - PGADMIN_LISTEN_ADDRESS=0.0.0.0
    - PGADMIN_LISTEN_PORT=8910
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
  mlflow:
    image: fletchjeffastro/astro_flight_demo:0.0.2
    networks:
      - airflow
    command: mlflow server --host 0.0.0.0 --backend-store-uri sqlite:////data/mlflow_backend.db --default-artifact-root /data
    volumes:
      - ${PWD}/include/mlflow:/data    
    ports:
      - 5000:5000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
  streamlit:
    image: fletchjeffastro/flight-streamlit:0.1.0
    networks:
      - airflow
    ports:
      - 8501:8501
    extra_hosts:
      - "host.docker.internal:host-gateway"  
    restart: always    
  webserver:
    extra_hosts:
      - "host.docker.internal:host-gateway"
  triggerer:
    extra_hosts:
      - "host.docker.internal:host-gateway"
  scheduler:
    extra_hosts:
      - "host.docker.internal:host-gateway"    