version: '2'
services:
  minio:
    image: quay.io/minio/minio
    networks:
      - airflow
    command: server /data --console-address ":9001"
    #streamlit run include/code/streamlit_app.py
    # volumes:
    #   - ${PWD}:/xray
    ports:
      - 9000:9000
      - 9001:9001
    # working_dir: /xray
  jupyter:
    image: tensorflow/tensorflow:latest-jupyter
    networks:
      - airflow
    volumes:
      - ${PWD}/:/notebook/
      # - ${PWD}/xray/data/:/data/
    ports:
      - 8888:8888
    command: bash -c "source /etc/bash.bashrc && jupyter notebook --notebook-dir=/notebook --ip 0.0.0.0 --no-browser --allow-root --NotebookApp.token=''"
